python/software/fullstack/apps/CRUD/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

# '''Handlings React Routes in Django'''

app_name = 'CRUD'
urlpatterns = [
    # Backend API
    path('api/surveys/', views.SurveyView.as_view(), name='api_surveys'),
    path('api/surveys/<int:pk>/', views.SurveyView.as_view()),
    # Frontend Django.py
    path('readme/', views.readme, name='readme'),
    # Frontend React.js
    path('edit/<path:url>/', views.page),
    path('<path:url>/', views.page, name='catch-all'),
    path('', views.page, name='crud'),
    path('create/', views.page, name='create'),
]

python/software/fullstack/configuration/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.CRUD.urls')),
]

python/software/fullstack/apps/CRUD/models.py
from django.db import models

class Survey(models.Model):
    respondentId = models.AutoField(primary_key=True)
    emailAddress = models.EmailField()
    dateCreated = models.DateTimeField(auto_now_add=True)
    dateUpdated = models.DateTimeField(auto_now=True)
    age = models.IntegerField()
    gender = models.CharField(max_length=10)
    Q1 = models.TextField()
    Q2 = models.TextField()
    Q3 = models.TextField()

    def __str__(self):
        return f"Survey {self.respondentId}: {self.emailAddress}"

# \fullstack> python manage.py sqlmigrate CRUD 0001  
# BEGIN;
# --
# -- Create model Survey
# --
# CREATE TABLE "CRUD_survey" ("respondentId" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "emailAddress" varchar(254) NOT NULL, "dateCreated" datetime NOT NULL, "dateUpdated" datetime NOT NULL, "age" integer NOT NULL, "gender" varchar(10) NOT NULL, "question1" text NOT NULL, "question2" text NOT NULL, "question3" text NOT NULL);
# COMMIT;

# {
    # "survey": {
        # "respondentId":1,
        # "emailAddress":"delta@growth-delta.com",
        # "dateCreated":"2023-05-14T10:00:00",
        # "dateUpdated":"2023-05-14T10:00:00",
        # "age":25,
        # "gender":"Male",
        # "Q1":"Yes",
        # "Q2":"Yes",
        # "Q3":"Yes"
    # }
# }

python/software/fullstack/apps/CRUD/views.py
from django.http.response import JsonResponse
from django.shortcuts import render

from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.permissions import AllowAny
from rest_framework import status
from django.http import Http404

from . models import Survey
from . serializers import SurveySerializer

# React Front-end
def page(request, url=None):
    return render(request, 'index.html')

# Django Front-end
def readme(request):
    return render(request, 'readme.html')

# API | Rest API
class SurveyView(APIView):
    permission_classes = [AllowAny]

    def get_survey(self, pk):
        try:
            return Survey.objects.get(respondentId=pk)
        except Survey.DoesNotExist:
            raise Http404("Survey does not exist.")

    def get(self, request, pk=None):
        if pk:
            survey = self.get_survey(pk)
            serializer = SurveySerializer(survey)
        else:
            surveys = Survey.objects.all()
            serializer = SurveySerializer(surveys, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def post(self, request):
        serializer = SurveySerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response("Survey posted successfully.", status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def put(self, request, pk=None):
        survey = self.get_survey(pk)
        serializer = SurveySerializer(instance=survey, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response("Survey updated successfully.", status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk=None):
        survey = self.get_survey(pk)
        survey.delete()
        return Response("Survey successfully deleted.", status=status.HTTP_204_NO_CONTENT)


   

python/software/fullstack/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="corporate">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block page_title %} Default SEO Title {% endblock %}</title>
        <meta name="description" content="{% block description %} Default SEO Description {% endblock %}">
        <meta name="keywords" content="{% block keywords %} Default SEO KeyWords {% endblock %}">
        <link rel="stylesheet" href="{% static 'bundles/css/tailwind-bundle.css' %}">
        <link rel="stylesheet" href="{% static 'bundles/css/style-bundle.css' %}">
        <!-- <link type="application/javascript" href="{% static 'bundles/js/tailwind-bundle.js' %}"> -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        {% block page_head %}
            <!-- <link rel="stylesheet" href="{% static '' %}"> -->
        {% endblock %}
    </head>
    <body class="min-h-screen">
        {% block body_wrapper %}
            <div class="bg-base-200">
                {% include 'components/navbar.html' %}
            </div>
            {% block body %}
                {% block content %}
                    <!-- index.html | React Frontend -->
                {% endblock content %}
            {% endblock body %}
            {% include 'components/footer.html' %}
        {% endblock body_wrapper %}
        <script type="text/javascript" src="{% static 'bundles/js/site-bundle.js' %}"></script>
        <script type="text/javascript" src="{% static 'javascript/SortTable.js' %}"></script>
        {% block page_js %}
        {% endblock page_js %}
    </body>
</html>

python/software/fullstack/templates/components/footer.html
{% load static %}
<div class="min-h-screen bg-base-200">
    <div class="hero">
        <div class="hero-content flex-col lg:flex-row-reverse mt-0">
            <img src="https://daisyui.com/images/stock/photo-1635805737707-575885ab0820.jpg" class="mask mask-squircle max-w-sm shadow-2xl" />
            <div>
                <h1 class="text-5xl font-bold">Box Office News!</h1>
                <p class="py-6">Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi.</p>
                <a href="{% url 'CRUD:readme' %}" class="btn btn-primary">Read Me</a>
            </div>
        </div>
    </div>
    <div class="text-center p-2"><kbd class="kbd">ctrl</kbd>+<kbd class="kbd">shift</kbd>+<kbd class="kbd">ANY Key</kbd></div>
    <div class="text-center p-2"><kbd class="kbd">Software ©</kbd></div>
</div>

python/software/fullstack/templates/components/navbar.html
{% load static %}
<div class="navbar container">
    <div class="navbar-start">
        

        <a href="/" class="normal-case text-xl">
            <label tabindex="0" class="btn btn-ghost btn-circle avatar">
                <div class="w-10 rounded-full">
                <img src="{% static 'images/logo.png' %}" />
                </div>
            </label>
        </a>
        
        <div class="dropdown">

        <label tabindex="0" class="btn btn-ghost lg:hidden">
            <i class="fa-solid fa-barcode fa-rotate-90 fa-xl"></i>
        </label>

    </div>

</div>

<div class="navbar-center hidden lg:flex">
</div>

<div class="navbar-end">
    <a href="{% url 'CRUD:readme' %}" class="btn">Read Me</a>
</div>

</div>

python/software/fullstack/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div id="root"></div>
{% endblock content %}
{% block page_js %}
  <script type="text/javascript" src="{% static 'bundles/js/CRUD-bundle.js' %}"></script>
{% endblock page_js %}

python/software/fullstack/templates/readme.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  {{content|safe}}
{% endblock content %}
{% block page_js %}
{% endblock page_js %}